package com.briup.apps.ej.dao;

import com.briup.apps.ej.bean.Order_line;
import com.briup.apps.ej.bean.Order_lineExample;
import java.util.List;

import com.briup.apps.ej.bean.extend.Order_line_Extend;
import org.apache.ibatis.annotations.Param;

public interface Order_lineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_order_line
     *
     * @mbg.generated Mon Jun 10 13:33:10 CST 2019
     */
    long countByExample(Order_lineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_order_line
     *
     * @mbg.generated Mon Jun 10 13:33:10 CST 2019
     */
    int deleteByExample(Order_lineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_order_line
     *
     * @mbg.generated Mon Jun 10 13:33:10 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_order_line
     *
     * @mbg.generated Mon Jun 10 13:33:10 CST 2019
     */
    int insert(Order_line record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_order_line
     *
     * @mbg.generated Mon Jun 10 13:33:10 CST 2019
     */
    int insertSelective(Order_line record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_order_line
     *
     * @mbg.generated Mon Jun 10 13:33:10 CST 2019
     */
    List<Order_line> selectByExample(Order_lineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_order_line
     *
     * @mbg.generated Mon Jun 10 13:33:10 CST 2019
     */
    Order_line selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_order_line
     *
     * @mbg.generated Mon Jun 10 13:33:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") Order_line record, @Param("example") Order_lineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_order_line
     *
     * @mbg.generated Mon Jun 10 13:33:10 CST 2019
     */
    int updateByExample(@Param("record") Order_line record, @Param("example") Order_lineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_order_line
     *
     * @mbg.generated Mon Jun 10 13:33:10 CST 2019
     */
    int updateByPrimaryKeySelective(Order_line record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_order_line
     *
     * @mbg.generated Mon Jun 10 13:33:10 CST 2019
     */
    int updateByPrimaryKey(Order_line record);


        //查询订单项通过id
       Order_line_Extend findAllOrder_lineById(Long id);

       //查询所有的订单项
       List<Order_line_Extend> findAllOrder_line();


}