package com.briup.apps.ej.service;

import com.briup.apps.ej.bean.Category;
import com.briup.apps.ej.bean.CategoryExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CategoryService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_category
     *
     * @mbg.generated Mon Jun 10 13:33:10 CST 2019
     */
    long countByExample(CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_category
     *
     * @mbg.generated Mon Jun 10 13:33:10 CST 2019
     */
    int deleteByExample(CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_category
     *
     * @mbg.generated Mon Jun 10 13:33:10 CST 2019
     */
    int deleteByPrimaryKey(Long id) throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_category
     *
     * @mbg.generated Mon Jun 10 13:33:10 CST 2019
     */
    int insert(Category record) throws  Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_category
     *
     * @mbg.generated Mon Jun 10 13:33:10 CST 2019
     */
    int insertSelective(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_category
     *
     * @mbg.generated Mon Jun 10 13:33:10 CST 2019
     */
    List<Category> selectByExample(CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_category
     *
     * @mbg.generated Mon Jun 10 13:33:10 CST 2019
     */
    Category selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_category
     *
     * @mbg.generated Mon Jun 10 13:33:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") Category record, @Param("example") CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_category
     *
     * @mbg.generated Mon Jun 10 13:33:10 CST 2019
     */
    int updateByExample(@Param("record") Category record, @Param("example") CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_category
     *
     * @mbg.generated Mon Jun 10 13:33:10 CST 2019
     */
    int updateByPrimaryKeySelective(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_category
     *
     * @mbg.generated Mon Jun 10 13:33:10 CST 2019
     */
    int updateByPrimaryKey(Category record) throws Exception;
}
